# -*- encoding: utf-8 -*-

=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "steamfitter/version"

Gem::Specification.new do |s|
  s.name        = "steamfitter"
  s.version     = Steamfitter::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["rimas silkaitis"]
  s.email       = ["rimas@meroxa.io"]
  s.homepage    = "https://github.com/neovintage/steamfitter"
  s.summary     = "REST Client for Conduit. Programmatically move data between data stores."
  s.description = "No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)"
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.1"

  s.add_runtime_dependency 'faraday', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
