=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module Steamfitter
  class ParameterValidationType
    UNSPECIFIED = "TYPE_UNSPECIFIED".freeze
    REQUIRED = "TYPE_REQUIRED".freeze
    GREATER_THAN = "TYPE_GREATER_THAN".freeze
    LESS_THAN = "TYPE_LESS_THAN".freeze
    INCLUSION = "TYPE_INCLUSION".freeze
    EXCLUSION = "TYPE_EXCLUSION".freeze
    REGEX = "TYPE_REGEX".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ParameterValidationType.constants.select { |c| ParameterValidationType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ParameterValidationType" if constantValues.empty?
      value
    end
  end
end
