=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Steamfitter::InformationServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InformationServiceApi' do
  before do
    # run before each test
    @api_instance = Steamfitter::InformationServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InformationServiceApi' do
    it 'should create an instance of InformationServiceApi' do
      expect(@api_instance).to be_instance_of(Steamfitter::InformationServiceApi)
    end
  end

  # unit tests for information_service_get_info
  # @param [Hash] opts the optional parameters
  # @return [Apiv1Info]
  describe 'information_service_get_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
