=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Steamfitter::Apiv1Info
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Steamfitter::Apiv1Info do
  let(:instance) { Steamfitter::Apiv1Info.new }

  describe 'test an instance of Apiv1Info' do
    it 'should create an instance of Apiv1Info' do
      expect(instance).to be_instance_of(Steamfitter::Apiv1Info)
    end
  end
  describe 'test attribute "version"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "os"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "arch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
