=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Steamfitter::ConnectorSourceState
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Steamfitter::ConnectorSourceState do
  let(:instance) { Steamfitter::ConnectorSourceState.new }

  describe 'test an instance of ConnectorSourceState' do
    it 'should create an instance of ConnectorSourceState' do
      expect(instance).to be_instance_of(Steamfitter::ConnectorSourceState)
    end
  end
  describe 'test attribute "position"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
