=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Steamfitter::ParameterValidationType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Steamfitter::ParameterValidationType do
  let(:instance) { Steamfitter::ParameterValidationType.new }

  describe 'test an instance of ParameterValidationType' do
    it 'should create an instance of ParameterValidationType' do
      expect(instance).to be_instance_of(Steamfitter::ParameterValidationType)
    end
  end
end
