=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Steamfitter::V1ExportPipelineResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Steamfitter::V1ExportPipelineResponse do
  let(:instance) { Steamfitter::V1ExportPipelineResponse.new }

  describe 'test an instance of V1ExportPipelineResponse' do
    it 'should create an instance of V1ExportPipelineResponse' do
      expect(instance).to be_instance_of(Steamfitter::V1ExportPipelineResponse)
    end
  end
  describe 'test attribute "pipeline"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
