=begin
#Conduit REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'steamfitter/api_client'
require 'steamfitter/api_error'
require 'steamfitter/version'
require 'steamfitter/configuration'

# Models
require 'steamfitter/models/apiv1_info'
require 'steamfitter/models/connector_destination_state'
require 'steamfitter/models/connector_source_state'
require 'steamfitter/models/googlerpc_status'
require 'steamfitter/models/inline_object'
require 'steamfitter/models/inline_object1'
require 'steamfitter/models/inline_object2'
require 'steamfitter/models/parameter_validation'
require 'steamfitter/models/parameter_validation_type'
require 'steamfitter/models/pipeline_state'
require 'steamfitter/models/plugin_specifications_parameter'
require 'steamfitter/models/plugin_specifications_parameter_type'
require 'steamfitter/models/processor_parent'
require 'steamfitter/models/processor_parent_type'
require 'steamfitter/models/protobuf_any'
require 'steamfitter/models/v1_connector'
require 'steamfitter/models/v1_connector_config'
require 'steamfitter/models/v1_connector_type'
require 'steamfitter/models/v1_create_connector_request'
require 'steamfitter/models/v1_create_connector_response'
require 'steamfitter/models/v1_create_pipeline_request'
require 'steamfitter/models/v1_create_pipeline_response'
require 'steamfitter/models/v1_create_processor_request'
require 'steamfitter/models/v1_create_processor_response'
require 'steamfitter/models/v1_export_pipeline_response'
require 'steamfitter/models/v1_get_connector_response'
require 'steamfitter/models/v1_get_info_response'
require 'steamfitter/models/v1_get_pipeline_response'
require 'steamfitter/models/v1_get_processor_response'
require 'steamfitter/models/v1_import_pipeline_response'
require 'steamfitter/models/v1_list_connectors_response'
require 'steamfitter/models/v1_list_pipelines_response'
require 'steamfitter/models/v1_list_plugins_response'
require 'steamfitter/models/v1_list_processors_response'
require 'steamfitter/models/v1_pipeline'
require 'steamfitter/models/v1_pipeline_config'
require 'steamfitter/models/v1_pipeline_status'
require 'steamfitter/models/v1_plugin_specifications'
require 'steamfitter/models/v1_processor'
require 'steamfitter/models/v1_processor_config'
require 'steamfitter/models/v1_processor_type'
require 'steamfitter/models/v1_update_connector_response'
require 'steamfitter/models/v1_update_pipeline_response'
require 'steamfitter/models/v1_update_processor_response'
require 'steamfitter/models/v1_validate_connector_request'

# APIs
require 'steamfitter/api/connector_service_api'
require 'steamfitter/api/information_service_api'
require 'steamfitter/api/pipeline_service_api'
require 'steamfitter/api/plugin_service_api'
require 'steamfitter/api/processor_service_api'

module Steamfitter
  class << self
    # Customize default settings for the SDK using block.
    #   Steamfitter.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
